language: node_js
sudo: false
node_js:
- '12'
before_script:
- npm install
script:
- npx nightwatch --env browserstack.chrome
env:
  global:
  - secure: Zwz8jM+Z+YHnkRGZTDQyhWJok0SR2s/r2u7wcrLrHReCDNmrUZyGF439MwnuWlZjZrz8gDUAMYDYFaCUhvTCkFDuzvE1hgZl7tcr1tX1h95c3mYy1H8ccgqz/OeV7fxVvBzA8SPCJcz9EJPXlAlR2REVMfDi3Q+U+i/tmJRlJ6eQRYGQnw+lhJKMLGeLXKfgHjZXPTkdpXzf8DHY2QM4QdFj2hgBuz/wacPrmjgRJvzvSKiAdtNh+GLeJGnGdF4dZS7VL6mbn0EelKCBS3H7XhyBbr5WqSsHLNJvafy3DpzlzMule8AKo90Ycf1/ii6yvNnLcmNZ2Yb7vidlP5zMXGTzdgcZHzFH5vTYyoWaZUE6KA0lDtlyXeo0rzE49lV83tg9Tl4+WGicCvrI6yAYNs4OkIULvcTcc2bTtFfB5D25iRTA2yQ6uLD5clrEt/4B0R0P7FoEqRIo6UbmH+W9T4E3kQcKDaurQkM25PQ44gNBsdVwndZMlRal5DpLFO83pu5/LyPeHAZIbVWBvDpjN3oJfuyP8Bz9NsR3fMaCb1r2rWq1m1TKkeHzT+do0FIFpUO/D2pwI7NCJlsT0I0Yick1F9I9cok5kwxfH9N6D520ltVe+ZUX8/FutgycqeEwLGcyq3+jMJiv4EtkbexAov/xl6hnakETre3GgWfjxQ4=
  - secure: fvenxyXzjvZ0o2fHGjd8lV6yhAFWm9+d2tn3DHmrrQxrGI3fqtmWH7WuaVRMP6+tzt23ruuI5ntDOKwyHifiDif1Q4v4QBsraJ02uBJPubzyEc9VdzyzZTKhg+l5IQmCzfgP/sGG+HnN+gV978ytbg4OnRhzOK+Ho5y8JsUHh3pmVs7sE11ewG0aSBC1Z+e2+j5fsWOmOLTBbnJUCDBoJlHDGYXteLdo7NqbBxHEKmZmWpiLBC71pxgFcuuIUj+MWgFJEeD96bMLTnmXQ/7pJt1f3Pp+zd1DRR5j+3UmP8Z25kOYpmDC+DzEFq+EvIqrNerJqxiYb84qsBKOgU6LccF0ZDRNwzHha6mPBbnbCAZsrZBfWRsBLRWoThDJ2Bn5/8TzcXzlmlIfExeiuSo6ZG1s5YVejeuhl13CoZplZCdyb8yAPkT/qzEYShXWMbRh/8PRoZgqSQNRaFOoGgFM61h89o5HwyqK5nOX7KMk/FkVB+0t/bBSjDItJ1Ppn22PGt9MM1UaFXjIE3Q5bjI3RpPbcrhK0pDR8gR/Wvxra5vfSv7NouXSuAB2q/REeMvXvYU0K50sekF8Zl4kp8GugF2hAugwUQYXdO7V053oAGldpb8MIOvjvXp8RSplRvW4bd35zXG68gmxPfi/FD5eqAEUDeSYl3IDVdSHYL75lPU=
